package com.cp.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-14T09:04:59.766+08:00
 * Generated source version: 3.2.1
 */
@WebService(targetNamespace = "http://webservice.cp.com/", name = "CalculateService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculateService {

    @WebMethod
    @RequestWrapper(localName = "generate", targetNamespace = "http://webservice.cp.com/", className = "com.cp.webservice.Generate")
    @ResponseWrapper(localName = "generateResponse", targetNamespace = "http://webservice.cp.com/", className = "com.cp.webservice.GenerateResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String generate(
            @WebParam(name = "configs", targetNamespace = "")
                    java.lang.String configs
    );

    @WebMethod
    @RequestWrapper(localName = "answer", targetNamespace = "http://webservice.cp.com/", className = "com.cp.webservice.Answer")
    @ResponseWrapper(localName = "answerResponse", targetNamespace = "http://webservice.cp.com/", className = "com.cp.webservice.AnswerResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String answer(
            @WebParam(name = "expression", targetNamespace = "")
                    java.lang.String expression
    );
}
