
package com.cp.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-14T09:04:59.672+08:00
 * Generated source version: 3.2.1
 */
public final class CalculateService_CalculateServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.cp.com/", "CalculateService");

    private CalculateService_CalculateServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculateService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CalculateService_Service ss = new CalculateService_Service(wsdlURL, SERVICE_NAME);
        CalculateService port = ss.getCalculateServiceImplPort();

        {
            System.out.println("Invoking generate...");
            java.lang.String _generate_configs = "";
            java.lang.String _generate__return = port.generate(_generate_configs);
            System.out.println("generate.result=" + _generate__return);


        }
        {
            System.out.println("Invoking answer...");
            java.lang.String _answer_expression = "";
            java.lang.String _answer__return = port.answer(_answer_expression);
            System.out.println("answer.result=" + _answer__return);


        }

        System.exit(0);
    }

}
