package com.cp.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-14T09:04:59.797+08:00
 * Generated source version: 3.2.1
 */
@WebServiceClient(name = "CalculateService",
        wsdlLocation = "http://localhost:8888/services/CalculateService?wsdl",
        targetNamespace = "http://webservice.cp.com/")
public class CalculateService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.cp.com/", "CalculateService");
    public final static QName CalculateServiceImplPort = new QName("http://webservice.cp.com/", "CalculateServiceImplPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/services/CalculateService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculateService_Service.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8888/services/CalculateService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculateService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculateService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculateService_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculateService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculateService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns CalculateService
     */
    @WebEndpoint(name = "CalculateServiceImplPort")
    public CalculateService getCalculateServiceImplPort() {
        return super.getPort(CalculateServiceImplPort, CalculateService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CalculateService
     */
    @WebEndpoint(name = "CalculateServiceImplPort")
    public CalculateService getCalculateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CalculateServiceImplPort, CalculateService.class, features);
    }

}
